spring.application.name=MagicLink

spring.datasource.url=jdbc:h2:file:C:/h2/ejemplo_magic_link
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

#Para construir el enlace del "correo". No se usa el Host de la peticion a proposito (se puede falsificar).
app.base-url=http://localhost:8080

#Clave simetrica HS256 para firmar el JWT final (la misma idea que en los proyectos SpringSecurity6_JWT)
app.jwt.clave-secreta=${CLAVE_JWT:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
