spring.application.name=ServicioExpedientes

#Mismo mapping que tenia el DispatcherServlet en el AppInitializer original ("/expedientesx/*")
spring.mvc.servlet.path=/expedientesx

#Esto sustituye al @Bean InternalResourceViewResolver de ConfiguracionMVC
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
